import = ["/home/riorq/.config/alacritty/themes/alacritty-theme/themes/riorkk.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#001014"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "Caskaydia Cove NF"
style = "Bold"

[font.bold_italic]
family = "Caskaydia Cove NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Caskaydia Cove NF"
style = "Italic"

[font.normal]
family = "Caskaydia Cove NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1.0

[window.padding]
x = 5
y = 5
